# Site settings
title: 摄氏零度
email: do.not@email.me
description: 分享内容，扩展思想……
baseurl: "/blog" # the subpath of your site, e.g. /blog/
excerpt_separator: <!--more-->
exclude: ["bower.json", "package.json", "bower_components", "node_modules"]

# Build settings
markdown: redcarpet

# server settings
host: 0.0.0.0
port: 8000