# Site settings
title: 摄氏零度
email: do.not@email.me
description: 分享内容，扩展思想……
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yuanjiachen.com" # the base hostname & protocol for your site
twitter_username: aquarior77
github_username:  jimyuan
sass:
  sass_dir: bower_components/bootstrap-sass-official/assets/stylesheets
gems: 
- jekyll-compass
excerpt_separator: <!--more-->
exclude: ["bower.json", "package.json", "bower_components", "node_modules"]

# Build settings
markdown: redcarpet